# GET all contacts
GET http://localhost:3000/users

###
# GET contact by ID
GET http://localhost:3000/users/67cecf3fbb3b9f73c3d1388e

###

# POST new contact
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "username": "test1",
  "name": "John",
  "ipaddress": "0.0.0.0/0"
}

###
# PUT update contact
PUT http://localhost:3000/users/67d45a9cd5b5612d35e9f5ae
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "username": "test2",
  "name": "James",
  "ipaddress": "0.0.0.0/0"
}

###
# DELETE contact
DELETE http://localhost:3000/users/67d599f47272910dd6c98632
