### Get all users
GET http://localhost:3000/clients
Content-Type: application/json

### Create a new user
POST http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Jordan",
  "lastName": "Tyrone",
  "username": "Jty",
  "password": "secure189",
  "email": "jtyrone@example.com",
  "favoriteColor": "Grey",
  "birthday": "16/April/1998",
  "ipaddress" : "0.0.0.0/0",
  "country": "Canada"
}

### Get a user by ID (Replace {id} with an actual user ID)
GET http://localhost:3000/clients/67daefbb595c7fa18a761c29
Content-Type: application/json

### Update a user by ID (Replace {id} with an actual user ID)
PUT http://localhost:3000/clients/67daefbb595c7fa18a761c29
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Babatunde",
  "username": "jbabaT",
  "password": "pass1",
  "email": "jbaba@gmail.com",
  "favoriteColor": "Green",
  "birthday": "29/June/1990",
  "ipaddress" : "0.0.0.0/0",
  "country": "Nigeria"
}

### Delete a user by ID (Replace {id} with an actual user ID)
DELETE http://localhost:3000/clients/67daef80595c7fa18a761c26
Content-Type: application/json
