# GET all contacts
GET http://localhost:3000/users

###
# GET contact by ID
GET http://localhost:3000/users/67d5a17d6f2c6bad0a6df3d2

###

# POST new contact
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test9@gmail.com",
  "username": "test9",
  "name": "Matthew",
  "ipaddress": "0.0.0.0/0"
}

###
# PUT update contact
PUT http://localhost:3000/users/67d5a44a29132201f8e6647e
Content-Type: application/json

{
  "email": "test10@gmail.com",
  "username": "test10",
  "name": "Frank",
  "ipaddress": "0.0.0.0/0"
}

###
# DELETE contact
DELETE http://localhost:3000/users/67cecf3fbb3b9f73c3d1388e
