# GET all contacts
GET http://localhost:3000/users

###
# GET contact by ID
GET http://localhost:3000/users/67d5a17d6f2c6bad0a6df3d2

###

# POST new contact
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName" : "Faithya",
  "lastName": "Mayor",
  "username": "test6",
  "email": "test6@gmail.com",
  "favoriteColor" : "Yellow",
  "birthday" : "14/September/1997",
  "ipaddress": "0.0.0.0/0"
}

###
# PUT update contact
PUT http://localhost:3000/users/67d84592b213616526ff9c4e
Content-Type: application/json

{
  "firstName" : "Moses",
  "lastName": "Matthew",
  "username": "test2",
  "email": "test2@gmail.com",
  "favoriteColor" : "Blue",
  "birthday" : "20/March/1986",
  "ipaddress": "0.0.0.0/0"
}

###
# DELETE contact
DELETE http://localhost:3000/users/67d5a4e729132201f8e6647f
